### ISSUE TITLE
updateStrategy in helm values not being used

### ISSUE THREAD

**Issue by karuppiah7890** [BaritoLog/helm-charts#1]
The `updateStrategy` in the values.yaml is not being used in the daemonset template in the `spec`

**Comment by karuppiah7890** [comment]
Tagging maintainers. cc @giosakti @tarabaskara @pushm0v

**Comment by giosakti** [comment]
do you mean updateStrategy here `https://github.com/BaritoLog/td-agent-barito-kubernetes/blob/master/helm/charts/td-agent-barito/values.yaml` does not have any effect?

**Comment by karuppiah7890** [comment]
Yes. Exactly. I thought it would change the `DaemonSet`'s update strategy. But it does not

**Comment by giosakti** [comment]
removed in https://github.com/BaritoLog/td-agent-barito-kubernetes/commit/4af5baadf0657c0183a2035e6a5c374de133290e
